language: node_js
node_js:
- 10.16.2
addons:
  apt:
    packages:
    - xvfb
before_install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
cache: npm
env:
  global:
    secure: LsdBvNbrRfEqUcwF0XW6pLzvAVlC8MFvLj1PpaGX2wrcWuDwLbfPl/KDfZBKoj4/abtM71NcjCRK5zUpeMVVG3o4vIQMxxEw+4SGyxpeo39SdE7NX+WC7sVoVfBkI+bWcjieQL26pgzFDFXZ0hkfhzrealRUvMsjmD7kvkv+mvWbmoQZC4A3MR3McPyj7++1mO9pC/l1sDQlJHxk6nrOA0S3fTdt85arbt1ThAsbDR4WZqvfhQ5Sd95VYyIVI35iWyUxx0Cgy3qTZH183LIu+w3Hgm/mSF9jAS1bXjHlDjeaAS5b3MerduTQztA9E0+mAoN9L5L2XDOdhSX1i1GM83DMKXM5kTnmIjqLecNCTreD/PuoThAm/52F6mDQ+0KIJNNFBLzV4KIJLokV/Y4M0pdoSmVSEpnGFYivQcb7U1+oXB84fT4NnA5nqv/65k7Wv8L7G0VNtJ03z1v8jbENMj+CFN3FQLKG7FgEEEMnNy//YNwPaF1REOiLJ02t02sy3XJHFl6crt6dWtXRxlhUDlMYmPaUNqmFsX/18bsPbuKp/1VID8wodpb88zLgRHwp+CudiZm2LLAgMhFY9/aDOYeGCwreRtN/S+jlxMHCD/U86U/N2l4joqvERIYDvY7UQVNy9AeyCFdqrzwGkgcWjnFA+BPKdIi2TEP5CtOEr2g=
