name: Build and Package for Linux

on:
  workflow_dispatch: # You can modify this to your main development branch

jobs:
  build:
    runs-on: ubuntu-latest # Using a Linux runner

    env: # Adding the environment variable for the GH_TOKEN
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15' # Use the specific version of Node that your project requires

      - name: Install Dependencies
        run: npm install

      - name: Build and Package for Linux
        run: npm run package-linux

      # Optional step to upload the Linux package as an artifact
      - name: Upload Linux Package
        uses: actions/upload-artifact@v2
        with:
          name: linux-app
          path: release/Swell-1.15.0.AppImage # Change the path according to your Linux build output

